### ISSUE TITLE
Is possible to use this plugin as init script for gradle ? 

### ISSUE THREAD

**Issue by lukasmrtvy** [nebula-plugins/gradle-lint-plugin#330]
Is possible to use this plugin as init script for gradle ? 
I am using ( 6.8.3-jdk11 ):
```
cat << EOF > lint.gradle
buildscript {
  repositories { mavenCentral() }
  dependencies {
    classpath 'com.netflix.nebula:gradle-lint-plugin:16.18.0'
  }
}
apply plugin: 'nebula.lint'
EOF
gradle --init-script lint.gradle
```
and getting:
```
* What went wrong:
A problem occurred evaluating initialization script.
> Plugin with id 'nebula.lint' not found.
```
Thanks

**Comment by rpalcolea** [comment]
I see that you got help in https://gradle-community.slack.com/archives/CAHSN3LDN/p1617723587155000?thread_ts=1617720982.153100&cid=CAHSN3LDN 

I'm closing this now 👍

**Comment by exaucae** [comment]
I was also interested in seeing the answer. After many searches, I managed to find a valid invitation link and access the slack message. That's a lot of work to see an answer.

If we want to keep Slack as the source of answers, we'll need to make it easy for people to join. Otherwise, it's also safe to duplicate the answer here.
