### ISSUE TITLE
[v5.1.0+] Ignoring duplicate-dependency-rule from centralized dependency definitions

### ISSUE THREAD

**Issue by dotnal** [nebula-plugins/gradle-lint-plugin#67]
Hi again,

First off, just wanted to say thanks for the hard work on this plugin! Heaps appreciated, and sorry for this long feedback loop:

Related to #42 and #43:

Configuration (gradle ver: 2.14)
```
gradleLint.rules = ['duplicate-dependency-class', 'overridden-dependency-version']
apply from: 'dependencies.gradle'
```
dependencies.gradle
```
ext.deps = [
    derby: "org.apache.derby:derby:10.4.2.0",
    derbytools: "org.apache.derby:derbytools:10.4.2.0"
]
```

Ignoring duplicate-dependency-class
```groovy
gradleLint.ignore('duplicate-dependency-class') {
    compile deps.derby
}
runtime deps.derbytools
```

generates the errors 
`org.apache.derby:derby:10.4.2.0 in configuration 'runtime' has 15 classes duplicated by org.apache.derby:derbytools:10.4.2.0 (no auto-fix available)`

`org.apache.derby:derby:10.4.2.0 in configuration 'compile' has 15 classes duplicated by org.apache.derby:derbytools:10.4.2.0 (no auto-fix available)`

This occurs from v5.1.0 upwards (after the fix for #43 was implemented).

**Comment by jkschneider** [comment]
@dotnal The root cause here is that Gradle Lint did not attempt to evaluate extension property-driven dependencies (including to determine which ones were ignored). I think there should be some limit on how much sophistication we should add for evaluating arbitrary code to identify dependencies, but I think defining dependencies with extension properties is common enough that it warrants support. This support is included in 6.1.0. 

Thanks for the continuing feedback!
